require 'stringio'

require 'terminal_output/styling/sgr'

require 'terminal_output/styling/color/mode/rgb'

require 'terminal_output/styling/color/palette/value'
require 'terminal_output/styling/color/palette/standard'
require 'terminal_output/styling/color/palette/high_intensity'
require 'terminal_output/styling/color/palette/eight_bit/value'
require 'terminal_output/styling/color/palette/eight_bit/standard'
require 'terminal_output/styling/color/palette/eight_bit/high_intensity'
require 'terminal_output/styling/color/palette/eight_bit/rgb'
require 'terminal_output/styling/color/palette/eight_bit/greyscale'
require 'terminal_output/styling/color/palette/eight_bit'
require 'terminal_output/styling/color/palette/twenty_four_bit'
require 'terminal_output/styling/color/palette/twenty_four_bit/value'
require 'terminal_output/styling/color/palette/twenty_four_bit/unabridged'
require 'terminal_output/styling/color/palette/twenty_four_bit/abridged'
require 'terminal_output/styling/color'

require 'terminal_output/styling/style'

require 'terminal_output/styling/trait'
require 'terminal_output/styling/trait/underline'
require 'terminal_output/styling/trait/blink'
require 'terminal_output/styling/trait/strikethrough'
require 'terminal_output/styling/trait/overline'
require 'terminal_output/styling/trait/font/weight'
require 'terminal_output/styling/trait/font/slant'
require 'terminal_output/styling/trait/font/fraktur'
require 'terminal_output/styling/trait/color/reverse_video'
require 'terminal_output/styling/trait/color/foreground'
require 'terminal_output/styling/trait/color/foreground/transparent'
require 'terminal_output/styling/trait/color/background'

require 'terminal_output/styling/write/raw'
require 'terminal_output/styling/write/raw/omit_styling'
require 'terminal_output/styling/write/raw/substitute'
require 'terminal_output/styling/write/raw/build'
require 'terminal_output/styling/write'
