require 'stringio'

require 'terminal_output/styling/sgr'

require 'terminal_output/styling/color/mode/rgb'

require 'terminal_output/styling/color/palette/value'
require 'terminal_output/styling/color/palette/standard'
require 'terminal_output/styling/color/palette/high_intensity'
require 'terminal_output/styling/color/palette/eight_bit/value'
require 'terminal_output/styling/color/palette/eight_bit/standard'
require 'terminal_output/styling/color/palette/eight_bit/high_intensity'
require 'terminal_output/styling/color/palette/eight_bit/rgb'
require 'terminal_output/styling/color/palette/eight_bit/greyscale'
require 'terminal_output/styling/color/palette/eight_bit'
require 'terminal_output/styling/color/palette/twenty_four_bit'
require 'terminal_output/styling/color/palette/twenty_four_bit/value'
require 'terminal_output/styling/color/palette/twenty_four_bit/unabridged'
require 'terminal_output/styling/color/palette/twenty_four_bit/abridged'
require 'terminal_output/styling/color'
