require 'terminal_output/styling/controls/sgr'

require 'terminal_output/styling/controls/color/mode/rgb/gradient'
require 'terminal_output/styling/controls/color/mode/rgb/scale'

require 'terminal_output/styling/controls/color'
require 'terminal_output/styling/controls/color/standard'
require 'terminal_output/styling/controls/color/high_intensity'
require 'terminal_output/styling/controls/color/eight_bit'
require 'terminal_output/styling/controls/color/eight_bit/standard'
require 'terminal_output/styling/controls/color/eight_bit/high_intensity'
require 'terminal_output/styling/controls/color/eight_bit/rgb'
require 'terminal_output/styling/controls/color/eight_bit/greyscale'
require 'terminal_output/styling/controls/color/twenty_four_bit'
require 'terminal_output/styling/controls/color/twenty_four_bit/unabridged'
require 'terminal_output/styling/controls/color/twenty_four_bit/abridged'

require 'terminal_output/styling/controls/style'

require 'terminal_output/styling/controls/trait'
require 'terminal_output/styling/controls/trait/underline'
require 'terminal_output/styling/controls/trait/blink'
require 'terminal_output/styling/controls/trait/strikethrough'
require 'terminal_output/styling/controls/trait/overline'
require 'terminal_output/styling/controls/trait/font/intensity'
